name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm/v7 -t jb75012/your_image_name:latest --push .

    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.RPI_HOST }}
        username: ${{ secrets.RPI_USER }}
        key: ${{ secrets.RPI_SSH_KEY }}
        script: |
          docker pull your_dockerhub_username/your_image_name:latest
          docker stop your_container_name || true
          docker rm your_container_name || true
          docker run -d --name your_container_name --restart always your_dockerhub_username/your_image_name:latest
